### ISSUE TITLE
Appcusive-API: errors on Tenant (Update,Add and Navigation properties CreatedBy, ModifiedBy)

### ISSUE THREAD

**Issue by ChrEggenberger** [dfensgmbh/biz.dfch.CS.Appclusive.UI#64]
* [x] Tenant does not have Navigation properties CreatedBy, ModifiedBy
* [x] No properties are saved on PATCH (no errors)
```
PATCH http://172.19.115.33/Appclusive/api/Core/Tenants(guid'11111111-1111-1111-1111-111111111111') HTTP/1.1
DataServiceVersion: 3.0;NetFx
MaxDataServiceVersion: 3.0;NetFx
Content-Type: application/json;odata=minimalmetadata
Accept: application/json;odata=minimalmetadata
Accept-Charset: UTF-8
User-Agent: Microsoft ADO.NET Data Services
Host: 172.19.115.33
Content-Length: 437
Expect: 100-continue

{"odata.type":"biz.dfch.CS.Appclusive.Core.OdataServices.Core.Tenant","Created":"2015-12-14T16:12:47.09Z","CreatedById":"1","Description":"SYSTEM_TENANT a","ExternalId":"11111111-1111-1111-1111-111111111111","ExternalType":"Internal","Id":"11111111-1111-1111-1111-111111111112","Modified":"2015-12-14T16:12:47.09Z","ModifiedById":"1","Name":"SYSTEM_TENANT a","ParentId":"11111111-1111-1111-1111-111111111111","RowVersion":"AAAAAAABSck="}
```

* [x] Exception on POST (add) HTTP 500
```
POST http://172.19.115.33/Appclusive/api/Core/Tenants HTTP/1.1
DataServiceVersion: 3.0;NetFx
MaxDataServiceVersion: 3.0;NetFx
Content-Type: application/json;odata=minimalmetadata
Accept: application/json;odata=minimalmetadata
Accept-Charset: UTF-8
User-Agent: Microsoft ADO.NET Data Services
Host: 172.19.115.33
Content-Length: 425
Expect: 100-continue

{"odata.type":"biz.dfch.CS.Appclusive.Core.OdataServices.Core.Tenant","Created":"2015-12-17T14:28:50.4556647+01:00","CreatedById":"1","Description":"Desc","ExternalId":"13f68a68-d017-4482-9bcc-bcca229da1c2","ExternalType":"Internal","Id":"13f68a68-d017-4482-9bcc-bcca229da1c2","Modified":"2015-12-17T14:28:50.4556647+01:00","ModifiedById":"1","Name":"TEST","ParentId":"22222222-2222-2222-2222-222222222222","RowVersion":null}
```

* [x] Add .Expand("CreatedBy").Expand("ModifiedBy") in TenantController

**Comment by rufer7** [comment]
@ChrEggenberger please test again. This should work now as well with `JSON`. At least it works when accessing the API (newest version deployed today) directly via browser

**Comment by rufer7** [comment]
@ChrEggenberger please test again. I fixed the bug when updating/saving Tenants and redeployed yesterday evening

**Comment by ChrEggenberger** [comment]
@rufer7  Creating new tenants works (POST) But Patch does still have the same problem. no exception but no data saved

**Comment by rufer7** [comment]
@ChrEggenberger thanks for the information. I actually saw in the code that some calls for validation and copy on patch were missing. I will add them and with the next release and deployment the functionality will be available.

**Comment by ChrEggenberger** [comment]
@rufer7  Navigation properties CreatedBy, ModifiedBy on Tenant are still missing (used for displaying in general tab). 
Maybe it just needs a new release of the biz.dfch.CS.Appclusive.Api nuget-package

**Comment by rufer7** [comment]
@ChrEggenberger because the Tenant entity is the only entity not deriving from BaseEntity the properties `CreatedBy` and `ModifiedBy` are not available on Tenant and won't be available. But you could load the user by Id using `CreatedById` and `ModifiedById`

**Comment by rufer7** [comment]
@ChrEggenberger where do we stand here?

**Comment by ChrEggenberger** [comment]
Working now

**Comment by rufer7** [comment]
@ChrEggenberger so we can close this issue?
